# This file was generated by GoReleaser. DO NOT EDIT.
cask "awssso" do
  name "awssso"
  desc "Writes credentials for AWS SSO'd accounts so that older applications can use them."
  homepage "https://github.com/webdestroya/aws-sso"
  version "1.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "awssso"

  on_macos do
    on_intel do
      url "https://github.com/webdestroya/aws-sso/releases/download/v#{version}/awssso_Darwin_x86_64.tar.gz"
      sha256 "55611e129b88d77a9c408a25dfdf1ffc04a12b755d90a4463ed2fd2ee28d2ab3"
    end
    on_arm do
      url "https://github.com/webdestroya/aws-sso/releases/download/v#{version}/awssso_Darwin_arm64.tar.gz"
      sha256 "d61a47635d69bea633515d636fdbb42bf310bf46c868b1573e8b765bda34e12d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/webdestroya/aws-sso/releases/download/v#{version}/awssso_Linux_x86_64.tar.gz"
      sha256 "31cca4af0a79faee848a0fcec6d365f159eaea29e97d5503478ad2f93da059de"
    end
    on_arm do
      url "https://github.com/webdestroya/aws-sso/releases/download/v#{version}/awssso_Linux_arm64.tar.gz"
      sha256 "1b1ec828342c384c249a226a4f0082a4ceaad9e8f7e60d4f618c5c8ae86e4688"
    end
  end

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/groundskeeper"]
  end

  # No zap stanza required
end
