# This file was generated by GoReleaser. DO NOT EDIT.
cask "groundskeeper" do
  name "groundskeeper"
  desc "Generic database migrations"
  homepage "https://github.com/webdestroya/groundskeeper"
  version "0.0.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "groundskeeper"

  on_macos do
    on_intel do
      url "https://github.com/webdestroya/groundskeeper/releases/download/v#{version}/groundskeeper_darwin_amd64.tar.gz"
      sha256 "b9b98bfc9831d1e6ffdaf3ef5dd4f4aefec7118352eb1a47804463443c76050b"
    end
    on_arm do
      url "https://github.com/webdestroya/groundskeeper/releases/download/v#{version}/groundskeeper_darwin_arm64.tar.gz"
      sha256 "96f6e4f24299c669c67b2c7402566e301aadc99eccb3ef97b512dfc5ce2acba4"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/webdestroya/groundskeeper/releases/download/v#{version}/groundskeeper_linux_amd64.tar.gz"
      sha256 "b8026bba889c499d4c38253def6559c9303655e0da17006663cf136d69e7d7ee"
    end
    on_arm do
      url "https://github.com/webdestroya/groundskeeper/releases/download/v#{version}/groundskeeper_linux_arm64.tar.gz"
      sha256 "a68a53ff71a34a9bdce917720b598e9dcaf421dd8227d2e18c7619059f6cf26e"
    end
  end

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/groundskeeper"]
  end

  # No zap stanza required
end
