# This file was generated by GoReleaser. DO NOT EDIT.
cask "groundskeeper" do
  name "groundskeeper"
  desc "Generic database migrations"
  homepage "https://github.com/webdestroya/groundskeeper"
  version "0.0.7"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "groundskeeper"

  on_macos do
    on_intel do
      url "https://github.com/webdestroya/groundskeeper/releases/download/v#{version}/groundskeeper_darwin_amd64.tar.gz"
      sha256 "c6ae182ee362d4d965aed33512077d74f38b3725b8f9e27a6fcb6b86b37bf2d4"
    end
    on_arm do
      url "https://github.com/webdestroya/groundskeeper/releases/download/v#{version}/groundskeeper_darwin_arm64.tar.gz"
      sha256 "199cb563f2c2bf3bb6b25a88a4e0aeaa768938e344de2e93a7a6ec406de21235"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/webdestroya/groundskeeper/releases/download/v#{version}/groundskeeper_linux_amd64.tar.gz"
      sha256 "5b1eac76147b553815bb9ec330dda186bcee888731078c5f2e6d0af39a7b68e0"
    end
    on_arm do
      url "https://github.com/webdestroya/groundskeeper/releases/download/v#{version}/groundskeeper_linux_arm64.tar.gz"
      sha256 "b97415b8b04ac9b7099361fa51f88e95e67721ca1e597efdd1e5214cfbde41e2"
    end
  end

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/groundskeeper"]
  end

  # No zap stanza required
end
