# This file was generated by GoReleaser. DO NOT EDIT.
cask "groundskeeper" do
  name "groundskeeper"
  desc "Generic database migrations"
  homepage "https://github.com/webdestroya/groundskeeper"
  version "0.0.6"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "groundskeeper"

  on_macos do
    on_intel do
      url "https://github.com/webdestroya/groundskeeper/releases/download/v#{version}/groundskeeper_darwin_amd64.tar.gz"
      sha256 "77f83eb0ed3e6c13ea0585486ea9c522ef3a809a1985f9849a22f30caecb00ad"
    end
    on_arm do
      url "https://github.com/webdestroya/groundskeeper/releases/download/v#{version}/groundskeeper_darwin_arm64.tar.gz"
      sha256 "187d6beffa9b05ade8451cfdcd4e35cb040dad2f1dea17ad98ecd8f2396d9ad1"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/webdestroya/groundskeeper/releases/download/v#{version}/groundskeeper_linux_amd64.tar.gz"
      sha256 "2b6cb7acd9c2f9e74a8154dfd51cb3fea428ac6c12ca4a192703b839ef6c92fb"
    end
    on_arm do
      url "https://github.com/webdestroya/groundskeeper/releases/download/v#{version}/groundskeeper_linux_arm64.tar.gz"
      sha256 "69d3f09f57a18900d4fafbea159ce0493bf09b610ed89aa943b092c54473f10f"
    end
  end

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/groundskeeper"]
  end

  # No zap stanza required
end
