# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Awssso < Formula
  desc "Writes credentials for AWS SSO'd accounts so that older applications can use them."
  homepage "https://github.com/webdestroya/aws-sso"
  version "1.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/webdestroya/aws-sso/releases/download/v1.0.1/awssso_Darwin_x86_64.tar.gz"
      sha256 "6b1eb6b436b867130243581949388f4f8fbc8b78d6ba91439bb2c628ed09a84b"

      def install
        bin.install "awssso"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/webdestroya/aws-sso/releases/download/v1.0.1/awssso_Darwin_arm64.tar.gz"
      sha256 "7d46ba1466eb808fa16dc734a8e390bceb1e4173ce06db497ce57fa86b69d55e"

      def install
        bin.install "awssso"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/webdestroya/aws-sso/releases/download/v1.0.1/awssso_Linux_x86_64.tar.gz"
        sha256 "affb2572501069884eb80aa107f415f94f76e7fd79dd2a95377bf7f9dc09fa0d"

        def install
          bin.install "awssso"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/webdestroya/aws-sso/releases/download/v1.0.1/awssso_Linux_arm64.tar.gz"
        sha256 "b422d4596027795cda9df9280a7feb244dee0a314829682a53762df9bb6eba6a"

        def install
          bin.install "awssso"
        end
      end
    end
  end

  test do
    system "#{bin}/awssso --help"
  end
end
