# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Awssso < Formula
  desc "Writes credentials for AWS SSO'd accounts so that older applications can use them."
  homepage "https://github.com/webdestroya/aws-sso"
  version "1.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/webdestroya/aws-sso/releases/download/v1.0.1/awssso_Darwin_x86_64.tar.gz"
      sha256 "5b4d4e84cd85422cf6a661633eb9f7ee9162c483c1b0745ae6cd41eb407666b3"

      def install
        bin.install "awssso"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/webdestroya/aws-sso/releases/download/v1.0.1/awssso_Darwin_arm64.tar.gz"
      sha256 "b0c3a79697df2b614eb5ff9d946516e071263a64053c366452e4811b7f0dd541"

      def install
        bin.install "awssso"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/webdestroya/aws-sso/releases/download/v1.0.1/awssso_Linux_x86_64.tar.gz"
        sha256 "a99edf9b9eeb36f6afc2db52766c97311ba1bc666252d4e0a034a2a2a5ea1597"

        def install
          bin.install "awssso"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/webdestroya/aws-sso/releases/download/v1.0.1/awssso_Linux_arm64.tar.gz"
        sha256 "c42b8f8de8db5382dd83d46f0d29c60c151ebe4b2edc87eb044566867fda76b9"

        def install
          bin.install "awssso"
        end
      end
    end
  end

  test do
    system "#{bin}/awssso --help"
  end
end
