# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RemoteShell < Formula
  desc "Allows easy remote access to containerized applications running on Fargate"
  homepage "https://github.com/webdestroya/remote-shell-client"
  version "0.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/webdestroya/remote-shell-client/releases/download/v0.0.2/remote-shell_darwin_arm64.zip"
      sha256 "c760865be7fae8e0cb94fc278b07189e6f7b64f4dee2d5e3d7416be8057a4cfa"

      def install
        bin.install "remote-shell"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/webdestroya/remote-shell-client/releases/download/v0.0.2/remote-shell_darwin_amd64.zip"
      sha256 "888ce8635c46c4edd34e88c2750b6fcebfc7ccd78c2398182025b77c071588b7"

      def install
        bin.install "remote-shell"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/webdestroya/remote-shell-client/releases/download/v0.0.2/remote-shell_linux_arm64.tar.gz"
      sha256 "febdc0f9abb6da5568eefd323bf99b9e113fb689c5811740a1f699ab63d67201"

      def install
        bin.install "remote-shell"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/webdestroya/remote-shell-client/releases/download/v0.0.2/remote-shell_linux_amd64.tar.gz"
      sha256 "9850173b4c5853ae91c487778285352493ade18fee4bff6d6bfaa4dfc4c7d846"

      def install
        bin.install "remote-shell"
      end
    end
  end
end
